# Generated by Django 4.2.6 on 2023-10-10 12:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0007_region_country_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breadpage",
            name="origin",
        ),
        migrations.AddField(
            model_name="breadpage",
            name="countries_of_origin",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="breads.country"
            ),
        ),
        migrations.AddField(
            model_name="breadpage",
            name="regions",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="breads.region"
            ),
        ),
    ]
