# Generated by Django 2.1.7 on 2019-03-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='profile_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
