# Generated by Django 4.0.8 on 2023-01-13 01:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRelatedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_related_page', to='blog.blogpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
