# Generated by Django 4.0.10 on 2023-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='version',
            field=models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light')], default='light', max_length=255),
        ),
    ]
